### ISSUE TITLE
CppClassesInPhp: Segmentation Fault when Calling property()

### ISSUE THREAD

**Issue by sjinks** [CopernicaMarketingSoftware/PHP-CPP#311]
Happens here (`Php::Value myMethod(Php::Parameters &params)`):

```c++
std::cout << "property1: " << property("property1") << std::endl;
```

```
Program received signal SIGSEGV, Segmentation fault.
0x00005555568f0031 in ?? ()
(gdb) bt
#0  0x00005555568f0031 in ?? ()
#1  0x00007fffed65d175 in Php::HashMember<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::operator Php::Value (this=0x7fffffffa0c0) at /usr/include/phpcpp/hashmember.h:85
#2  0x00007fffed65c8a7 in MyCustomClass::myMethod (this=0x55555698cfd0, params=...) at cppclassinphp.cpp:74
#3  0x00007fffed65d95e in Php::ZendCallable::invoke<MyCustomClass, &MyCustomClass::myMethod> (execute_data=0x7fffee0142c0, return_value=0x7fffee014110) at /usr/include/phpcpp/zendcallable.h:257
#4  0x0000555555dc60bf in ZEND_DO_FCALL_SPEC_HANDLER () at /tmp/php-build/source/7.0.9/Zend/zend_vm_execute.h:842
#5  0x0000555555dc49c6 in execute_ex (ex=0x7fffee014030) at /tmp/php-build/source/7.0.9/Zend/zend_vm_execute.h:414
#6  0x0000555555dc4bc7 in zend_execute (op_array=0x7fffee088000, return_value=0x0) at /tmp/php-build/source/7.0.9/Zend/zend_vm_execute.h:458
#7  0x0000555555d5c3cf in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /tmp/php-build/source/7.0.9/Zend/zend.c:1427
#8  0x0000555555c968e4 in php_execute_script (primary_file=0x7fffffffc8c0) at /tmp/php-build/source/7.0.9/main/main.c:2494
#9  0x0000555555e33feb in do_cli (argc=7, argv=0x5555567afca0) at /tmp/php-build/source/7.0.9/sapi/cli/php_cli.c:974
#10 0x0000555555e3548e in main (argc=7, argv=0x5555567afca0) at /tmp/php-build/source/7.0.9/sapi/cli/php_cli.c:1344
```

```
#0  0x00005555568f0031 in ?? ()
No symbol table info available.
#1  0x00007fffed65d175 in Php::HashMember<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::operator Php::Value (this=0x7fffffffa0c0) at /usr/include/phpcpp/hashmember.h:85
No locals.
#2  0x00007fffed65c8a7 in MyCustomClass::myMethod (this=0x55555698cfd0, params=...) at cppclassinphp.cpp:74
        v = {<Php::HashParent> = {_vptr.HashParent = 0x7fffffffa0d0}, _val = {_buffer = {__data = "Р\377\377\377\177\000\000N=>\355\377\177\000", __align = {<No data fields>}}}}
        now = {<Php::Value> = {<Php::HashParent> = {_vptr.HashParent = 0x7fffed865840 <vtable for Php::HashMember<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >+16>}, _val = {_buffer = {
                __data = "\340\240\377\377\377\177\000\000\t\000\000\000\000\000\000", __align = {<No data fields>}}}}, <No data fields>}
        obj = {<Php::Value> = {<Php::HashParent> = {_vptr.HashParent = 0x7fffed865840 <vtable for Php::HashMember<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >+16>}, _val = {_buffer = {
                __data = "\340\240\377\377\377\177\000\000\t\000\000\000\000\000\000", __align = {<No data fields>}}}}, <No data fields>}
#3  0x00007fffed65d95e in Php::ZendCallable::invoke<MyCustomClass, &MyCustomClass::myMethod> (execute_data=0x7fffee0142c0, return_value=0x7fffee014110) at /usr/include/phpcpp/zendcallable.h:257
        result = {<Php::HashParent> = {_vptr.HashParent = 0x7fffee002078}, _val = {_buffer = {__data = "\220\034\217VUU\000\000\001\000\000\000@\000\000", __align = {<No data fields>}}}}
        params = {<std::vector<Php::Value, std::allocator<Php::Value> >> = std::vector of length 1, capacity 1 = {{<Php::HashParent> = {_vptr.HashParent = 0x7fffed646270 <vtable for Php::Value+16>}, _val = {_buffer = {
                  __data = "\001\000\000\000\000\000\000\000\004\000\000\000\000\000\000", __align = {<No data fields>}}}}}, _object = 0x55555698cfd0}
```

Valgrind:
```
MyCustomClass::MyCustomClass()
myMethod is called for object 3
vex amd64->IR: unhandled instruction bytes: 0xE 0x0 0x0 0x0 0x0 0x11 0x0 0x0
vex amd64->IR:   REX=0 REX.W=0 REX.R=0 REX.X=0 REX.B=0
vex amd64->IR:   VEX=0 VEX.L=0 VEX.nVVVV=0x0 ESC=NONE
vex amd64->IR:   PFX.66=0 PFX.F2=0 PFX.F3=0
==26960== Warning: client switching stacks?  SP change: 0xffeffbf58 --> 0x10040a8
==26960==          to suppress, use: --max-stackframe=68685889200 or greater
==26960== valgrind: Unrecognised instruction at address 0xedd0033.
==26960==    at 0xEDD0033: ???
```

With `USE_ZEND_ALLOC=0`:
```
==29448== Jump to the invalid address stated on the next line
==29448==    at 0xEDD0031: ???
==29448==    by 0xF59A8A6: MyCustomClass::myMethod(Php::Parameters&) (cppclassinphp.cpp:73)
==29448==    by 0xF59B95D: void Php::ZendCallable::invoke<MyCustomClass, &MyCustomClass::myMethod>(_zend_execute_data*, _zval_struct*) (zendcallable.h:257)
==29448==    by 0x97A0BE: ZEND_DO_FCALL_SPEC_HANDLER (zend_vm_execute.h:842)
==29448==    by 0x9789C5: execute_ex (zend_vm_execute.h:414)
==29448==    by 0x978BC6: zend_execute (zend_vm_execute.h:458)
==29448==    by 0x9103CE: zend_execute_scripts (zend.c:1427)
==29448==    by 0x84A8E3: php_execute_script (main.c:2494)
==29448==    by 0x9E7FEA: do_cli (php_cli.c:974)
==29448==    by 0x9E948D: main (php_cli.c:1344)
==29448==  Address 0xedd0031 is 8 bytes after a block of size 25 alloc'd
==29448==    at 0x4C2CB3F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29448==    by 0x6630E70: xmlStrdup (in /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.4)
==29448==    by 0x65CA488: xmlHashUpdateEntry3 (in /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.4)
==29448==    by 0x724FCFF: xsltRegisterExtModuleFunction (in /usr/lib/x86_64-linux-gnu/libxslt.so.1.1.29)
==29448==    by 0x5056806: exsltRegisterAll (in /usr/lib/x86_64-linux-gnu/libexslt.so.0.8.17)
==29448==    by 0x764A5E: zm_startup_xsl (php_xsl.c:140)
==29448==    by 0x9192E4: zend_startup_module_ex (zend_API.c:1849)
==29448==    by 0x91936E: zend_startup_module_zval (zend_API.c:1864)
==29448==    by 0x928A74: zend_hash_apply (zend_hash.c:1534)
==29448==    by 0x9199D2: zend_startup_modules (zend_API.c:1975)
==29448==    by 0x849C6F: php_module_startup (main.c:2217)
==29448==    by 0x9E6B15: php_cli_startup (php_cli.c:423)
==29448== 
==29448== Invalid read of size 1
==29448==    at 0xEDD0031: ???
==29448==    by 0xF59A8A6: MyCustomClass::myMethod(Php::Parameters&) (cppclassinphp.cpp:73)
==29448==    by 0xF59B95D: void Php::ZendCallable::invoke<MyCustomClass, &MyCustomClass::myMethod>(_zend_execute_data*, _zval_struct*) (zendcallable.h:257)
==29448==    by 0x97A0BE: ZEND_DO_FCALL_SPEC_HANDLER (zend_vm_execute.h:842)
==29448==    by 0x9789C5: execute_ex (zend_vm_execute.h:414)
==29448==    by 0x978BC6: zend_execute (zend_vm_execute.h:458)
==29448==    by 0x9103CE: zend_execute_scripts (zend.c:1427)
==29448==    by 0x84A8E3: php_execute_script (main.c:2494)
==29448==    by 0x9E7FEA: do_cli (php_cli.c:974)
==29448==    by 0x9E948D: main (php_cli.c:1344)
==29448==  Address 0xedd0031 is 8 bytes after a block of size 25 alloc'd
==29448==    at 0x4C2CB3F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29448==    by 0x6630E70: xmlStrdup (in /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.4)
==29448==    by 0x65CA488: xmlHashUpdateEntry3 (in /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.4)
==29448==    by 0x724FCFF: xsltRegisterExtModuleFunction (in /usr/lib/x86_64-linux-gnu/libxslt.so.1.1.29)
==29448==    by 0x5056806: exsltRegisterAll (in /usr/lib/x86_64-linux-gnu/libexslt.so.0.8.17)
==29448==    by 0x764A5E: zm_startup_xsl (php_xsl.c:140)
==29448==    by 0x9192E4: zend_startup_module_ex (zend_API.c:1849)
==29448==    by 0x91936E: zend_startup_module_zval (zend_API.c:1864)
==29448==    by 0x928A74: zend_hash_apply (zend_hash.c:1534)
==29448==    by 0x9199D2: zend_startup_modules (zend_API.c:1975)
==29448==    by 0x849C6F: php_module_startup (main.c:2217)
==29448==    by 0x9E6B15: php_cli_startup (php_cli.c:423)
```

**Comment by sjinks** [comment]
```c++
// Crashes
std::cout << "property1: " << property("property1") << std::endl;
// Works
std::cout << "property1: " << Php::Value(this).get("property1") << std::endl;
```

**Comment by sjinks** [comment]
It looks like `_parent` gets spoilt somewhere:

```c++
    // HashMember::value()
    Value value() const
    {
        std::cerr << dynamic_cast<HashMember<Type>*>(_parent);
        return _parent->get(_index);
    }
```

With this I get

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff16a5bd0 in __dynamic_cast () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
```

gdb says:
```
(gdb) bt
#0  0x00007ffff16a5bd0 in __dynamic_cast () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007fffed65bf95 in Php::HashMember<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::value (this=0x7fffffffa0c0) at /usr/include/phpcpp/hashmember.h:76
#2  0x00007fffed3fbc21 in Php::operator<< (stream=..., value=...) at zend/hashmember.cpp:33
#3  0x00007fffed65b99b in MyCustomClass::myMethod (this=0x55555698d020, params=...) at cppclassinphp.cpp:73
#4  0x00007fffed65ca92 in Php::ZendCallable::invoke<MyCustomClass, &MyCustomClass::myMethod> (execute_data=0x7fffee0142c0, return_value=0x7fffee014110) at /usr/include/phpcpp/zendcallable.h:257
#5  0x0000555555dc60bf in ZEND_DO_FCALL_SPEC_HANDLER () at /tmp/php-build/source/7.0.9/Zend/zend_vm_execute.h:842
#6  0x0000555555dc49c6 in execute_ex (ex=0x7fffee014030) at /tmp/php-build/source/7.0.9/Zend/zend_vm_execute.h:414
#7  0x0000555555dc4bc7 in zend_execute (op_array=0x7fffee088000, return_value=0x0) at /tmp/php-build/source/7.0.9/Zend/zend_vm_execute.h:458
#8  0x0000555555d5c3cf in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /tmp/php-build/source/7.0.9/Zend/zend.c:1427
#9  0x0000555555c968e4 in php_execute_script (primary_file=0x7fffffffc8c0) at /tmp/php-build/source/7.0.9/main/main.c:2494
#10 0x0000555555e33feb in do_cli (argc=7, argv=0x5555567afca0) at /tmp/php-build/source/7.0.9/sapi/cli/php_cli.c:974
#11 0x0000555555e3548e in main (argc=7, argv=0x5555567afca0) at /tmp/php-build/source/7.0.9/sapi/cli/php_cli.c:1344
(gdb) frame 1
#1  0x00007fffed65bf95 in Php::HashMember<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::value (this=0x7fffffffa0c0) at /usr/include/phpcpp/hashmember.h:76
76              std::cerr << dynamic_cast<HashMember<Type>*>(_parent);
(gdb) print *_parent
$1 = {_vptr.HashParent = 0x7ffff199ce20 <std::cout>}
```

Why `_parent` turns into `std::cout` is a mystery.

**Comment by sjinks** [comment]
Looks like the issue is connected with the life time of temporary variables.

This code does not crash:

```c++
        Php::Value t(this);
        Php::HashMember<std::string> hm = t.operator[]("property1");
        Php::Value v = hm.value();
        std::cout << "property1: " << v << std::endl;
```

This one crashes:
```c++
        Php::HashMember<std::string> hm = Php::Value(this).operator[]("property1");
        Php::Value v = hm.value();
        std::cout << "property1: " << v << std::endl;
```

As far as I understand, in the second case `Php::Value(this)` gets destroyed after assignment to `hm`, and then `hm.value()` returns garbage / crashes.

To prove:

1. Annotate the program flow with `std::cerr << __PRETTY_FUNCTION__ << std::endl`:
```diff
diff --git a/include/base.h b/include/base.h
index 023d711..8770477 100644
--- a/include/base.h
+++ b/include/base.h
@@ -79,6 +79,7 @@ public:
      */
     HashMember<std::string> property(const char *name)
     {
+        std::cerr << __PRETTY_FUNCTION__ << std::endl;
         return Value(this)[name];
     }
 
@@ -89,6 +90,7 @@ public:
      */
     HashMember<std::string> property(const std::string &name)
     {
+        std::cerr << __PRETTY_FUNCTION__ << std::endl;
         return Value(this)[name];
     }
 
@@ -119,6 +121,7 @@ public:
      */
     Value property(const char *name) const
     {
+        std::cerr << __PRETTY_FUNCTION__ << std::endl;
         return Value(this).get(name);
     }
 
@@ -129,6 +132,7 @@ public:
      */
     Value property(const std::string &name) const
     {
+        std::cerr << __PRETTY_FUNCTION__ << std::endl;
         return Value(this).get(name);
     }

diff --git a/include/hashmember.h b/include/hashmember.h
index 378ee90..23b2cc8 100644
--- a/include/hashmember.h
+++ b/include/hashmember.h
@@ -35,7 +35,7 @@ public:
      *  @param  parent
      *  @param  index
      */
-    HashMember(HashParent *parent, Type index) : _parent(parent), _index(index) {}
+    HashMember(HashParent *parent, Type index) : _parent(parent), _index(index) { std::cerr << __PRETTY_FUNCTION__ << " " << index << std::endl; }

     /**
      *  Destructor
@@ -73,6 +73,7 @@ public:
      */
     Value value() const
     {
+        std::cerr << __PRETTY_FUNCTION__ << std::endl;
         return _parent->get(_index);
     }

@@ -82,6 +83,7 @@ public:
      */
     operator Value () const
     {
+        std::cerr << __PRETTY_FUNCTION__ << std::endl;
         return _parent->get(_index);
     }

diff --git a/zend/hashmember.cpp b/zend/hashmember.cpp
index f6f8483..cba3777 100644
--- a/zend/hashmember.cpp
+++ b/zend/hashmember.cpp
@@ -30,6 +30,7 @@ std::ostream &operator<<(std::ostream &stream, const HashMember<int> &value)
  */
 std::ostream &operator<<(std::ostream &stream, const HashMember<std::string> &value)
 {
+    std::cerr << __PRETTY_FUNCTION__ << std::endl;
     return stream << value.value();
 }

diff --git a/zend/value.cpp b/zend/value.cpp
index a50d499..235bc01 100644
--- a/zend/value.cpp
+++ b/zend/value.cpp
@@ -185,6 +185,7 @@ Value::Value(const Base *object)
     // set it to an object and increase refcount
     ZVAL_OBJ(_val, impl->php());
     Z_ADDREF_P(_val);
+    std::cerr << __PRETTY_FUNCTION__ << " " << (void*)_val << std::endl;
 }

 /**
@@ -265,6 +266,7 @@ Value::Value(Value &&that)  _NOEXCEPT
  */
 Value::~Value()
 {
+    std::cerr << __PRETTY_FUNCTION__ << " " << (void*)_val << std::endl;
     zval_ptr_dtor(_val);
 }
```
2. Modify `myMethod`:
```diff
diff --git a/Examples/CppClassesInPhp/cppclassinphp.cpp b/Examples/CppClassesInPhp/cppclassinphp.cpp
index 22ed4b8..8fedb9b 100644
--- a/Examples/CppClassesInPhp/cppclassinphp.cpp
+++ b/Examples/CppClassesInPhp/cppclassinphp.cpp
@@ -70,8 +70,8 @@ public:

         std::cout << "myMethod is called for object " << _x << std::endl;

-        std::cout << "property1: " << property("property1") << std::endl;
-
+        std::cout << "property1: " << std::flush;
+        std::cout << property("property1") << std::endl;

         return Php::Object("MyClass", new MyCustomClass(100));

```
3. Compile and run:
```
$ make -B -j6 CXXFLAGS="-g3" && sudo make install
$ cd Examples/CppClassesInPhp
$ $(phpenv which php) -n -d extension_dir=. -d extension=phpclassesincpp.so cppclassinphp.php
MyCustomClass::MyCustomClass()
myMethod is called for object 3
property1: Php::HashMember<std::__cxx11::basic_string<char> > Php::Base::property(const char*)
Php::Value::Value(const Php::Base*) 0x7ffc5855b0c0
Php::HashMember<Type>::HashMember(Php::HashParent*, Type) [with Type = std::__cxx11::basic_string<char>] property1
virtual Php::Value::~Value() 0x7ffc5855b0c0
std::ostream& Php::operator<<(std::ostream&, const Php::HashMember<std::__cxx11::basic_string<char> >&)
Php::Value Php::HashMember<Type>::value() const [with Type = std::__cxx11::basic_string<char>]
pure virtual method called
terminate called without an active exception
Aborted (core dumped)
```

Thus, `Php::Value(this)` gets destroyed before `HashMember<std::string>::value()` is called.

I am not sure what the solution should be in this case: I would probably remove all methods returning `HashMember<T>` from `Base`, as there exists no `HashMember::operator=(HashMember const&)`, and `HashMember<T>` will be converted to `Value` anyway (and the application would crash).

**Comment by sanmai** [comment]
Have you found where it ends after all?

**Comment by sjinks** [comment]
It was many years ago :-) It was related to the lifetime of temporary objects.
