### ISSUE TITLE
Segfault on inexistent static method call

### ISSUE THREAD

**Issue by vedadkajtaz** [CopernicaMarketingSoftware/PHP-CPP#340]
Hello,

Extension built with phpcpp segfaults when invoking an inexistent method of an extension-provided class.

Extension code:

```
#include "phpcpp.h"

#include <iostream>

void	existing_method(Php::Parameters &params)
{
	Php::out << params[0] << std::endl;
}

extern "C" {

    PHPCPP_EXPORT void *get_module()
    {
        static Php::Extension extension("dummy", "0.1");

		Php::Class<Php::Base>	dummyClass("dummyClass");

		dummyClass.method<existing_method>("existing_method", Php::Public, {
			Php::ByVal("whatever", Php::Type::String),
		});

		extension.add(std::move(dummyClass));

        return extension;
    }
}
```
Php:

```
#!/usr/bin/env php
<?php

dl('dummy.so');

dummyClass::existing_method('hello world');

dummyClass::this_will_segfault();

```

Output:

```
$./dummy.php
hello world
Segmentation fault (core dumped)

```

Stack trace:

```
#0  0x00000000006044bb in ZEND_INIT_STATIC_METHOD_CALL_SPEC_CONST_CONST_HANDLER ()
#1  0x00000000005d46b8 in execute_ex ()
#2  0x00000000005d499c in zend_execute ()
#3  0x0000000000590b96 in zend_execute_scripts ()
#4  0x000000000052cc56 in php_execute_script ()
#5  0x000000000063b5ab in do_cli ()
#6  0x000000000063a6d0 in main ()
```

Occurs as well with FPM SAPI.

Environment:

```
$ php -v
PHP 7.1.3 (cli) (built: Apr 11 2017 13:08:01) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.3, Copyright (c) 1999-2017, by Zend Technologies
```

Kind regards,

**Comment by vedadkajtaz** [comment]
Oops, duplicate of #309
